### ISSUE TITLE
Nothing being logged

### ISSUE THREAD

**Issue by HamishBlank** [mosesdinakaran/magento-log#1]
I'm running Magento 2.4.2 and installed the extension through composer (v2.0.11) however no logs are being generated, I have 
"Enabled for all APIs" selected in the configuration settings.

**Comment by mosesdinakaran** [comment]
Hi,

Can you please share me any environment to look in to this.

Regards,
Moses.

**Comment by mosesdinakaran** [comment]
Verified this in Magento  2.4.2 and it working as expected. Checked in both Developer and Production Mode.
Are you still facing this issue ?
If yes, Can you please check the below points

- Is your log folder writable
- Have you cleared the cache after enabling the extension
- Is there any error you see in the error logs file

This logic is very simple just using a plugin to log the API calls
You can debug this in this file \Moses\Log\Plugin\Magento\Webapi\Controller\RestPlugin::afterDispatch
Check if the execution is coming here.

If you still not able to have this working plz let me know.

**Comment by mosesdinakaran** [comment]
Closing this issue as there is no response from the Reporter.
